---
# PHP
#
# Install PHP and libraries
- name: "PHP: Install PHP and libraries."
  apt: >
    pkg={{ item }}
    state=installed
  with_items:
    - php5
    - php5-common
    - php5-mysql
    - php5-cli
    - php5-curl
    - php5-gd
    - php5-dev
    - php5-mcrypt
    - php-apc
    - php-pear
