---
# MySQL
#
# Install MySQL
- name: "MySQL: Install MySQL."
  apt: >
    pkg={{ item }}
    state=installed
  with_items:
    - python-mysqldb
    - mysql-server

- name: "MySQL: Start MySQL."
  service: name=mysql state=started enabled=yes

- name: "MySQL: Remove the MySQL test database."
  mysql_db: db=test state=absent

- name: "MySQL: Create database for multisite."
  mysql_db: >
    db={{ site }}
    state=present
